pipeline {
    agent {
        label 'jenkins-slave6.yvu.ch'
    }
    stages {
        stage('build') {
            steps {
                sh 'echo build'
                sh 'cd Gadgeothek; ./gradlew build'
            }
            post {
                always {
                    archiveArtifacts 'Gadgeothek/app/build/outputs/apk/*.apk'
                 }
            }
        }

        stage('End2End Tests')
        {
            steps {
                sh 'echo End2End Tests'
            }
        }

        stage('deployment')
        {
            steps {
                sh 'echo deployment'
            }
        }
    }
}